### ISSUE TITLE
bem-tools отказывается собирать проект

### ISSUE THREAD

**Issue by kompolom** [bem/bem-core-php#3]
bem-tools ругается 

```
Error: level module <project>/libs/bem-core-php/desktop.blocks/.bem/level.js can not be found 
```

Похоже `desktop.blocks/.bem/level.js` хочет подключить файл из корня библиотеки, а там как раз нет папки `.bem`...
Нужны ли папки `.bem` в `desktop.blocks` и `common.blocks`? Без них все нормально собирается

**Comment by qfox** [comment]
Опс. Видимо, я не все перенес, не было возможности потестировать ;-( по идее, там просто файлики нужны, чтобы bem-tools их воспринял как уровни.

Можешь протестировать и прислать PR?

**Comment by qfox** [comment]
cc @tadatuta А нужны ли эти папки для bem-tools?

**Comment by kompolom** [comment]
попробовал просто добавить папку `.bem` от `bem-core` в корень. начал ругаться

```
Error: Tech module with path '<project>/libs/bem-core-php/libs/bem-core/.bem/techs/browser.js.js' not found
```
