### ISSUE TITLE
Не запускаются тесты.

### ISSUE THREAD

**Issue by kompolom** [bem/bem-core-php#4]
все делал по аналогии с `bem-core`. https://github.com/kompolom/bem-core#development
Ругается сначала на отсутствие `.bem` или `.enb` потом на зависимости технологий...

**Comment by kompolom** [comment]
Кажется, тут есть связь с issue #3

**Comment by qfox** [comment]
а разве тесты в бемтулзах собираются? кажется, что это чисто enb-bem-tmpl-specs.

**Comment by kompolom** [comment]
Я имел ввиду, если ты добавишь конфиги в репозиторий, то запустятся и тесты и bem-tools

**Comment by qfox** [comment]
@kompolom Сорри, что так долго не отвечал. Я думаю, что можно добавить файлы с загрузкой уровней из bem-core: `module.exports = require('./libs/bem-core/.bem/levels.js');`

Кстати, у себя не пробовал? Можешь PR прислать? ;-)
